name = "yallamart-upload"
main = "worker.js"
compatibility_date = "2024-01-01"

[ai]
binding = "AI"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "yallamart-photos"

[[queues.producers]]
binding = "IMG_QUEUE"
queue = "yallamart-img-queue"

[[queues.consumers]]
queue = "yallamart-img-queue"
max_batch_size = 5
max_batch_timeout = 10
max_retries = 3

[[queues.producers]]
binding = "BROADCAST_QUEUE"
queue = "yallamart-broadcast-queue"

[[queues.consumers]]
queue = "yallamart-broadcast-queue"
max_batch_size = 5
max_batch_timeout = 10
max_retries = 3
